### ISSUE TITLE
Exceeded current quota

### ISSUE THREAD

**Issue by MitoKafander** [huntboom/PebbleGPT#4]
![16889924705112365890175425005026](https://github.com/huntboom/PebbleGPT/assets/60237079/a6bf15e3-2877-4d94-a447-5a2984888dfb)
I have the api inserted in the settings page. I get this message that my quota has been used. I haven't used chatgpt that often and when looking at the usage page it seems i have not used it that much.
![SmartSelect_20230710_153732_Brave](https://github.com/huntboom/PebbleGPT/assets/60237079/da2f0410-9ad6-40f0-8188-e7983a0d5231)

Do I need a paid account to use this app?

**Comment by huntboom** [comment]
if you look at the free trial usage it says the $18.00 credit granted expired December 2022, so you'd need either another account or to switch to the paid/billed version in your settings in order to use the app. I use PebbleGPT extensively and haven't been billed more than a few cents per month personally so I would recommend it.
